name: 张玉洁的组件-tif/confluence
description: 
keywords:
  - 张玉洁的标签
  - network
  - websocket


license: MMMMMMM                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

logo: http://192.168.0.178:8090/download/attachments/27396104/bmp.bmp
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
